service: bemcare-mailer-test
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude:
        - aws-serverless-express

package:
  include:
    - templates/**

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  memorySize: 256
  timeout: 30

functions:
  main:
    handler: ./src/lambda.handler
    reservedConcurrency: 2
    events:
      - http:
          method: any
          path: /{any+}